# Use the official Python image as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /supermart

# Copy the current directory contents into the container at /app
COPY . /supermart/

# Install Flask and requests module
RUN pip install Flask requests

# Expose port 5000 to allow communication to/from server
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "main.py"]
